Check that container exists before calling `removeChildren`
michalochman/react-pixi-fiber pull request #286
Opened 2022-10-08 18:40 UTC by kyle-villeneuve

This addresses an error I've repeatedly encountered in production (may have something to do with `React.Suspense` and/or `React.lazy` imports. Just ensures that the container exists before attempting to remove it.

```
TypeError: Cannot read properties of null (reading 'removeChildren')
	at removeChildren (../../src/ReactPixiFiber.js:122:12)
	at xb (../../node_modules/react-reconciler/cjs/react-reconciler.production.min.js:131:296)
	at Jf (../../node_modules/react-reconciler/cjs/react-reconciler.production.min.js:174:304)
	at ih (../../node_modules/react-reconciler/cjs/react-reconciler.production.min.js:171:235)
	at vc (../../node_modules/react-reconciler/cjs/react-reconciler.production.min.js:36:324)
	at Pc (../../node_modules/react-reconciler/cjs/react-reconciler.production.min.js:169:278)
	at Zg (../../node_modules/react-reconciler/cjs/react-reconciler.production.min.js:160:369)
```

2022-10-09 09:39 UTC, michalochman requested changes
Thanks @kyle-villeneuve! Seems like an obvious fix. I will merge and release it if you can update code formatting.

2022-10-09 09:39 UTC, michalochman commented on src/ReactPixiFiber.js
> +  container && container.removeChildren();
We use more verbose syntax in this repository:
```suggestion
  if (container) {
    container.removeChildren();
  }
```

2022-10-10 20:20 UTC, kyle-villeneuve commented
Ok, I've committed your suggestion, thanks. @michalochman

2022-10-11 10:01 UTC, michalochman approved these changes

2022-10-11 10:31 UTC, merged

2022-10-11 10:48 UTC, michalochman commented
@kyle-villeneuve thanks! The fix is now included in `react-pixi-fibet@1.0.3`.